// Next
import type { Metadata } from "next";

// Components
import Header from "@/components/header";
import Footer from "@/components/footer";

// Internationalization
import { Locale, i18n } from "../../../i18n.config";

// Styles
import "../../styles/globals.css";

export const metadata: Metadata = {
  title: "F1Calendar",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className="flex flex-col justify-between font-mono min-h-screen">
        <Header lang={params.lang}/>
        <main>{children}</main>
        <Footer lang={params.lang} />
      </body>
    </html>
  );
}
